version: "3.0"

services:

  instance:
    build: 
      context: '.'
    restart: "unless-stopped"
    ports:
      - "${ENV_HTTP_PORT:-80}:80"
      - "${ENV_HTTPS_PORT:-443}:443"
      - "${ENV_SSH_PORT:-22}:22"
    volumes:
      - "${ENV_DATA:-./data}:/home/web/public_html"
