version: "3.0"
services:
  sc_iasa:
    container_name: "sc_iasa"
    build: 
      context: './sc_iasa'
    restart: "unless-stopped"
    volumes:
      - "${SC_DATA_PATH}:/home/web/public_html"
    ports:
      - "${SC_SSH_PORT}:22"
      - "${SC_HTTP_PORT}:80"
      - "${SC_HTTPS_PORT}:443"