FROM ubuntu:latest
LABEL maintainer="Camamber"

RUN apt-get update && apt-get -y upgrade 
RUN apt-get install -y sudo supervisor openssh-server
RUN useradd -m -p "$(openssl passwd -1 qwerty123)" -s /bin/bash admin
RUN usermod -aG sudo admin
RUN update-rc.d supervisor defaults

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

WORKDIR /etc/supervisor/conf.d
EXPOSE 2222 8080

CMD ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
